import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "fr" | "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    "dashboard.welcome": "Bienvenue",
    "dashboard.today": "Aujourd'hui",
    "dashboard.quick_access": "Accès rapide",
    "dashboard.mood": "Enregistrer l'humeur",
    "dashboard.journal": "Écrire dans le journal",
    "dashboard.breathing": "Exercice de respiration",
    "dashboard.chat": "Parler à l'IA",
    "dashboard.stats": "Statistiques",
    "dashboard.mood_entries": "Entrées d'humeur",
    "dashboard.journal_entries": "Entrées du journal",
    "dashboard.exercises": "Exercices complétés",
    "dashboard.notifications": "Notifications",
    "dashboard.recent_activity": "Activité récente",
    "dashboard.recent_entries": "Dernières entrées",
    "dashboard.recent_exercises": "Exercices récents",
    "dashboard.no_entries": "Aucune entrée encore",
    "dashboard.no_exercises": "Aucun exercice encore",
    "dashboard.streak": "Streak",
    "dashboard.days": "jours",
    "dashboard.achievements": "Médailles",
    "dashboard.leaderboard": "Classement",
    "dashboard.challenges": "Défis",
    "dashboard.export": "Exporter",
    "dashboard.today_mood": "Votre humeur aujourd'hui",
    "dashboard.update": "Mettre à jour",
    "dashboard.mood_recorded": "Vous avez déjà enregistré votre humeur aujourd'hui. Continuez votre journée avec sérénité!",
    "dashboard.mood_prompt": "Comment vous sentez-vous aujourd'hui? Commencez par enregistrer votre humeur.",
    "mood.title": "Suivi de l'humeur",
    "mood.description": "Comment vous sentez-vous en ce moment? Enregistrez votre état émotionnel.",
    "mood.select": "Sélectionnez votre humeur",
    "mood.emotions_felt": "Émotions ressenties",
    "mood.very_sad": "Très triste",
    "mood.sad": "Triste",
    "mood.neutral": "Neutre",
    "mood.happy": "Bien",
    "mood.very_happy": "Très heureux",
    "mood.energy": "Niveau d'énergie",
    "mood.stress": "Niveau de stress",
    "mood.energy_low": "Très faible",
    "mood.energy_high": "Très élevé",
    "mood.stress_low": "Très calme",
    "mood.stress_high": "Très stressé",
    "mood.notes": "Notes (optionnel)",
    "mood.notes_placeholder": "Écrivez vos pensées ou ce qui influence votre humeur...",
    "mood.save": "Enregistrer l'humeur",
    "mood.update": "Mettre à jour l'humeur",
    "mood.saving": "Enregistrement...",
    "mood.saved": "Humeur enregistrée avec succès!",
    "mood.error": "Erreur lors de l'enregistrement de l'humeur",
    "mood.select_error": "Veuillez sélectionner votre humeur",
    "mood.emotion_happy": "Heureux",
    "mood.emotion_sad": "Triste",
    "mood.emotion_anxious": "Anxieux",
    "mood.emotion_calm": "Calme",
    "mood.emotion_energetic": "Énergique",
    "mood.emotion_tired": "Fatigué",
    "mood.emotion_frustrated": "Frustré",
    "mood.emotion_motivated": "Motivé",
    "mood.emotion_lonely": "Seul",
    "mood.emotion_connected": "Connecté",
    "journal.title": "Journal personnel",
    "journal.description": "Écrivez vos pensées et réflexions dans un espace sûr et privé.",
    "journal.new_entry": "Nouvelle entrée",
    "journal.title_input": "Titre",
    "journal.title_placeholder": "Titre de l'entrée",
    "journal.content_input": "Contenu",
    "journal.content_placeholder": "Écrivez vos pensées...",
    "journal.rating": "Évaluation du jour",
    "journal.save": "Enregistrer",
    "journal.saving": "Enregistrement...",
    "journal.update": "Mettre à jour",
    "journal.delete": "Supprimer",
    "journal.edit": "Éditer",
    "journal.cancel": "Annuler",
    "journal.select": "Sélectionnez une entrée ou créez-en une nouvelle",
    "journal.confirm_delete": "Êtes-vous sûr de vouloir supprimer cette entrée?",
    "journal.confirm_edit": "Êtes-vous sûr de vouloir mettre à jour cette entrée?",
    "journal.deleting": "Suppression...",
    "journal.updating": "Mise à jour...",
    "journal.created": "Entrée créée avec succès!",
    "journal.updated": "Entrée mise à jour!",
    "journal.deleted": "Entrée supprimée",
    "journal.error_required": "Le titre et le contenu sont obligatoires",
    "journal.error_create": "Erreur lors de la création",
    "journal.error_update": "Erreur lors de la mise à jour",
    "journal.error_delete": "Erreur lors de la suppression",
    "breathing.title": "Exercices de respiration",
    "breathing.description": "Guidez-vous à travers des techniques de respiration et de relaxation.",
    "breathing.select_button": "Sélectionner",
    "breathing.duration": "Durée",
    "breathing.minutes": "minutes",
    "breathing.box": "Box Breathing",
    "breathing.box_desc": "Respirez en carré: 4s inhale, 4s retenue, 4s exhale, 4s retenue",
    "breathing.4_7_8": "Respiration 4-7-8",
    "breathing.4_7_8_desc": "Technique apaisante: 4s inhale, 7s retenue, 8s exhale",
    "breathing.deep": "Respiration profonde",
    "breathing.deep_desc": "Respirations profondes et lentes pour se détendre",
    "breathing.meditation": "Méditation guidée",
    "breathing.meditation_desc": "Méditation courte pour la pleine conscience",
    "breathing.start": "Commencer",
    "breathing.pause": "Pause",
    "breathing.resume": "Reprendre",
    "breathing.complete": "Terminer l'exercice",
    "breathing.completing": "Enregistrement...",
    "breathing.cancel": "Annuler",
    "breathing.inhale": "Inspirez...",
    "breathing.hold": "Retenez...",
    "breathing.exhale": "Expirez...",
    "breathing.breathe": "Respirez",
    "breathing.relaxation": "Comment vous sentez-vous? (1-5)",
    "breathing.very_stressed": "Très stressé",
    "breathing.very_relaxed": "Très relaxé",
    "breathing.saved": "Exercice enregistré!",
    "breathing.error": "Erreur lors de l'enregistrement",
    "chat.title": "Assistant IA",
    "chat.description": "Parlez à Sérénité, votre assistant de bien-être mental bienveillant.",
    "chat.send": "Envoyer",
    "chat.placeholder": "Écrivez votre message...",
    "chat.clear": "Effacer",
    "chat.confirm_clear": "Êtes-vous sûr de vouloir effacer toutes les conversations?",
    "chat.clearing": "...",
    "chat.cleared": "Toutes les conversations ont été supprimées",
    "chat.error_clear": "Erreur lors de la suppression",
    "chat.greeting": "Bonjour! Je suis Sérénité. Comment puis-je vous aider aujourd'hui?",
    "progress.title": "Suivi des progrès",
    "progress.description": "Visualisez votre bien-être et vos progrès au fil du temps.",
    "progress.avg_mood": "Humeur moyenne",
    "progress.avg_energy": "Énergie moyenne",
    "progress.entries": "Entrées enregistrées",
    "progress.trend": "Tendance de l'humeur",
    "progress.comparison": "Comparaison des niveaux",
    "progress.no_data": "Aucune donnée disponible. Commencez à enregistrer votre humeur!",
    "progress.no_data_short": "Aucune donnée disponible.",
    "progress.mood_label": "Humeur",
    "progress.energy_label": "Énergie",
    "progress.stress_label": "Stress",
    "profile.title": "Mon profil",
    "profile.description": "Gérez vos préférences et paramètres personnels.",
    "profile.personal_info": "Informations personnelles",
    "profile.name": "Nom",
    "profile.email": "Email",
    "profile.bio": "Biographie",
    "profile.bio_placeholder": "Parlez de vous...",
    "profile.reminders": "Rappels et notifications",
    "profile.mood_reminder": "Heure du rappel d'humeur",
    "profile.journal_reminder": "Heure du rappel de journal",
    "profile.notifications": "Activer les notifications",
    "profile.save": "Enregistrer les préférences",
    "profile.saving": "Enregistrement...",
    "profile.saved": "Préférences mises à jour!",
    "profile.error": "Erreur lors de la mise à jour",
    "profile.logout": "Déconnexion",
    "profile.logout_desc": "Cliquez sur le bouton ci-dessous pour vous déconnecter de Sérénité.",
    "profile.disconnect": "Se déconnecter",
    "profile.disconnecting": "Déconnexion...",
    "profile.logout_success": "Déconnexion réussie",
    "profile.logout_error": "Erreur lors de la déconnexion",
    "settings.title": "Paramètres",
    "settings.manage": "Gérez vos préférences et paramètres généraux",
    "settings.language": "Langue",
    "settings.select_language": "Sélectionnez votre langue préférée",
    "settings.theme": "Thème",
    "settings.select_theme": "Choisissez votre thème préféré",
    "settings.theme_light": "Clair",
    "settings.theme_dark": "Sombre",
    "settings.notifications": "Notifications",
    "settings.privacy": "Confidentialité",
    "settings.account": "Compte actuel",
    "settings.user": "Utilisateur",
    "settings.change_name": "Changer le nom",
    "settings.change_name_desc": "Mettez à jour votre nom d'utilisateur",
    "settings.new_name": "Nouveau nom",
    "settings.update_name": "Mettre à jour le nom",
    "settings.name_updated": "Nom mis à jour avec succès!",
    "settings.confirm_name": "Êtes-vous sûr de vouloir changer votre nom?",
    "settings.logout": "Déconnexion",
    "settings.logout_desc": "Cliquez pour vous déconnecter et accéder à une autre compte",
    "settings.disconnect": "Se déconnecter",
    "settings.disconnecting": "Déconnexion...",
    "settings.logout_success": "Déconnexion réussie",
    "settings.logout_error": "Erreur lors de la déconnexion",
    "settings.name_error_empty": "Le nom ne peut pas être vide",
    "settings.name_update_error": "Erreur lors de la mise à jour",
    "settings.confirm": "Confirmer",
    "settings.cancel": "Annuler",
    "leaderboard.title": "Classement global",
    "leaderboard.description": "Comparez votre streak avec d'autres utilisateurs",
    "leaderboard.rank": "Rang",
    "leaderboard.user": "Utilisateur",
    "leaderboard.streak": "Streak",
    "leaderboard.achievements": "Médailles",
    "leaderboard.no_users": "Aucune donnée de classement disponible",
    "leaderboard.tip_title": "Conseil",
    "leaderboard.tip_description": "Maintenez votre streak en faisant votre enregistrement d'humeur quotidien. Plus vous avez de jours consécutifs, plus haut vous monterez dans le classement global.",
    "leaderboard.anonymous_user": "Utilisateur Anonyme",
    "challenges.title": "Défis hebdomadaires",
    "challenges.description": "Complétez les défis pour gagner des récompenses",
    "challenges.progress": "Progrès",
    "challenges.reward": "Récompense",
    "challenges.completed": "Complété",
    "challenges.auto_progress": "Le progrès se met à jour automatiquement en fonction de vos actions",
    "challenges.no_challenges": "Aucun défi disponible cette semaine",
    "challenges.how_it_works": "Comment fonctionnent les défis",
    "challenges.tip_1": "Complétez les défis hebdomadaires pour gagner des points",
    "challenges.tip_2": "Les points contribuent à votre classement global",
    "challenges.tip_3": "Nouveaux défis chaque semaine avec des objectifs différents",
    "challenges.tip_4": "Partagez vos réalisations avec la communauté",
    "achievements.title": "Vos Médailles",
    "achievements.no_unlocked": "Vous n'avez pas encore déverrouillé de médailles. Maintenez votre streak et déverrouillez des jalons spéciaux!",
    "achievements.milestones": "Prochains Jalons",
    "achievements.milestone_7": "Semaine d'Or",
    "achievements.milestone_30": "Mois Parfait",
    "achievements.milestone_100": "Centenaire",
    "achievements.milestone_365": "Champion de l'Année",
    "achievements.days_of_streak": "jours de streak",
    "common.points": "points",
    "nav.dashboard": "Tableau de bord",
    "nav.mood": "Humeur",
    "nav.journal": "Journal",
    "nav.breathing": "Respiration",
    "nav.chat": "Chat",
    "nav.progress": "Progrès",
    "nav.profile": "Profil",
    "nav.settings": "Paramètres",
    "nav.leaderboard": "Classement",
    "nav.challenges": "Défis",
    "nav.rewards": "Récompenses",
    "nav.export": "Exporter",
    "nav.logout": "Déconnexion",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.confirm": "Confirmer",
    "common.close": "Fermer",
    "rewards.shop_title": "Boutique de récompenses",
    "rewards.shop_description": "Utilisez vos points pour débloquer des récompenses exclusives",
    "rewards.your_points": "Vos points disponibles",
    "rewards.insufficient_points": "Points insuffisants",
    "rewards.redeem_button": "Utiliser",
    "rewards.already_redeemed": "Déjà utilisé",
    "rewards.redeemed_success": "Récompense utilisée avec succès!",
    "rewards.redeem_error": "Erreur lors de l'utilisation de la récompense",
    "rewards.no_rewards": "Aucune récompense disponible",
    "rewards.how_it_works": "Comment ça marche",
    "rewards.tip_1": "Complétez les défis pour gagner des points",
    "rewards.tip_2": "Accumulez des points avec votre streak quotidienne",
    "rewards.tip_3": "Utilisez vos points pour des récompenses exclusives",
    "rewards.tip_4": "Débloquez de nouvelles fonctionnalités",
    "export.title": "Exporter le Progrès",
    "export.description": "Téléchargez un rapport complet de votre progrès sur Sérénité",
    "export.personalized_report": "Votre Rapport Personnalisé",
    "export.download_html": "Téléchargez un rapport HTML avec:",
    "export.general_stats": "Statistiques générales",
    "export.unlocked_medals": "Médailles déverrouillées",
    "export.mood_history": "Historique de l'humeur",
    "export.report_format": "Le rapport sera téléchargé au format HTML et pourra être ouvert dans n'importe quel navigateur ou imprimé en PDF.",
    "export.generating": "Génération...",
    "export.download_button": "Télécharger le Rapport",
    "export.total_points": "Points Totaux",
    "export.medals": "Médailles",
    "export.mood_entries": "Entrées d'Humeur",
    "export.journal_entries": "Entrées de Journal",
    "export.tips_title": "Conseils",
    "export.tip_1": "Téléchargez votre rapport régulièrement pour suivre votre progrès",
    "export.tip_2": "Vous pouvez imprimer le rapport depuis votre navigateur (Ctrl+P ou Cmd+P)",
    "export.tip_3": "Partagez vos réalisations avec des amis ou des professionnels de la santé mentale",
    "export.tip_4": "Les rapports incluent les données jusqu'à la date actuelle",
    "streak": "Racha",
  },
  es: {
    "dashboard.welcome": "Bienvenido",
    "dashboard.today": "Hoy",
    "dashboard.quick_access": "Acceso rápido",
    "dashboard.mood": "Registrar humor",
    "dashboard.journal": "Escribir en diario",
    "dashboard.breathing": "Ejercicio de respiración",
    "dashboard.chat": "Hablar con IA",
    "dashboard.stats": "Estadísticas",
    "dashboard.mood_entries": "Registros de humor",
    "dashboard.journal_entries": "Entradas del diario",
    "dashboard.exercises": "Ejercicios completados",
    "dashboard.notifications": "Notificaciones",
    "dashboard.recent_activity": "Actividad reciente",
    "dashboard.recent_entries": "Últimas entradas",
    "dashboard.recent_exercises": "Ejercicios recientes",
    "dashboard.no_entries": "Sin entradas aún",
    "dashboard.no_exercises": "Sin ejercicios aún",
    "dashboard.streak": "Racha",
    "dashboard.days": "días",
    "dashboard.achievements": "Medallas",
    "dashboard.leaderboard": "Ranking",
    "dashboard.challenges": "Desafíos",
    "dashboard.export": "Exportar",
    "dashboard.today_mood": "Tu humor hoy",
    "dashboard.update": "Actualizar",
    "dashboard.mood_recorded": "Ya registraste tu humor hoy. ¡Continúa tu día con serenidad!",
    "dashboard.mood_prompt": "¿Cómo te sientes hoy? Comienza registrando tu humor.",
    "mood.title": "Seguimiento del humor",
    "mood.description": "¿Cómo te sientes en este momento? Registra tu estado emocional.",
    "mood.select": "Selecciona tu humor",
    "mood.emotions_felt": "Emociones sentidas",
    "mood.very_sad": "Muy triste",
    "mood.sad": "Triste",
    "mood.neutral": "Neutral",
    "mood.happy": "Bien",
    "mood.very_happy": "Muy feliz",
    "mood.energy": "Nivel de energía",
    "mood.stress": "Nivel de estrés",
    "mood.energy_low": "Muy bajo",
    "mood.energy_high": "Muy alto",
    "mood.stress_low": "Muy tranquilo",
    "mood.stress_high": "Muy estresado",
    "mood.notes": "Notas (opcional)",
    "mood.notes_placeholder": "Escribe tus pensamientos o lo que influye en tu humor...",
    "mood.save": "Guardar humor",
    "mood.update": "Actualizar humor",
    "mood.saving": "Guardando...",
    "mood.saved": "¡Humor guardado con éxito!",
    "mood.error": "Error al guardar el humor",
    "mood.select_error": "Por favor selecciona tu humor",
    "mood.emotion_happy": "Feliz",
    "mood.emotion_sad": "Triste",
    "mood.emotion_anxious": "Ansioso",
    "mood.emotion_calm": "Tranquilo",
    "mood.emotion_energetic": "Enérgico",
    "mood.emotion_tired": "Cansado",
    "mood.emotion_frustrated": "Frustrado",
    "mood.emotion_motivated": "Motivado",
    "mood.emotion_lonely": "Solo",
    "mood.emotion_connected": "Conectado",
    "journal.title": "Diario personal",
    "journal.description": "Escribe tus pensamientos y reflexiones en un espacio seguro y privado.",
    "journal.new_entry": "Nueva entrada",
    "journal.title_input": "Título",
    "journal.title_placeholder": "Título de la entrada",
    "journal.content_input": "Contenido",
    "journal.content_placeholder": "Escribe tus pensamientos...",
    "journal.rating": "Calificación del día",
    "journal.save": "Guardar",
    "journal.saving": "Guardando...",
    "journal.update": "Actualizar",
    "journal.delete": "Eliminar",
    "journal.edit": "Editar",
    "journal.cancel": "Cancelar",
    "journal.select": "Selecciona una entrada o crea una nueva",
    "journal.confirm_delete": "¿Estás seguro de que deseas eliminar esta entrada?",
    "journal.confirm_edit": "¿Estás seguro de que deseas actualizar esta entrada?",
    "journal.deleting": "Eliminando...",
    "journal.updating": "Actualizando...",
    "journal.created": "¡Entrada creada con éxito!",
    "journal.updated": "¡Entrada actualizada!",
    "journal.deleted": "Entrada eliminada",
    "journal.error_required": "El título y el contenido son obligatorios",
    "journal.error_create": "Error al crear la entrada",
    "journal.error_update": "Error al actualizar",
    "journal.error_delete": "Error al eliminar",
    "breathing.title": "Ejercicios de respiración",
    "breathing.description": "Guíate a través de técnicas de respiración y relajación.",
    "breathing.select_button": "Seleccionar",
    "breathing.duration": "Duración",
    "breathing.minutes": "minutos",
    "breathing.box": "Box Breathing",
    "breathing.box_desc": "Respira en cuadrado: 4s inhala, 4s retén, 4s exhala, 4s retén",
    "breathing.4_7_8": "Respiración 4-7-8",
    "breathing.4_7_8_desc": "Técnica calmante: 4s inhala, 7s retén, 8s exhala",
    "breathing.deep": "Respiración profunda",
    "breathing.deep_desc": "Respiraciones profundas y lentas para relajarse",
    "breathing.meditation": "Meditación guiada",
    "breathing.meditation_desc": "Meditación corta para la atención plena",
    "breathing.start": "Comenzar",
    "breathing.pause": "Pausa",
    "breathing.resume": "Reanudar",
    "breathing.complete": "Terminar ejercicio",
    "breathing.completing": "Guardando...",
    "breathing.cancel": "Cancelar",
    "breathing.inhale": "Inhala...",
    "breathing.hold": "Retén...",
    "breathing.exhale": "Exhala...",
    "breathing.breathe": "Respira",
    "breathing.relaxation": "¿Cómo te sientes? (1-5)",
    "breathing.very_stressed": "Muy estresado",
    "breathing.very_relaxed": "Muy relajado",
    "breathing.saved": "¡Ejercicio guardado!",
    "breathing.error": "Error al guardar el ejercicio",
    "chat.title": "Asistente IA",
    "chat.description": "Habla con Sérénité, tu asistente de bienestar mental.",
    "chat.send": "Enviar",
    "chat.placeholder": "Escribe tu mensaje...",
    "chat.clear": "Borrar",
    "chat.confirm_clear": "¿Estás seguro de que deseas borrar todas las conversaciones?",
    "chat.clearing": "...",
    "chat.cleared": "Todas las conversaciones han sido eliminadas",
    "chat.error_clear": "Error al eliminar las conversaciones",
    "chat.greeting": "¡Hola! Soy Sérénité. ¿Cómo puedo ayudarte hoy?",
    "progress.title": "Seguimiento de progreso",
    "progress.description": "Visualiza tu bienestar y progreso a lo largo del tiempo.",
    "progress.avg_mood": "Humor promedio",
    "progress.avg_energy": "Energía promedio",
    "progress.entries": "Entradas registradas",
    "progress.trend": "Tendencia del humor",
    "progress.comparison": "Comparación de niveles",
    "progress.no_data": "Sin datos disponibles. ¡Comienza a registrar tu humor!",
    "progress.no_data_short": "Sin datos disponibles.",
    "progress.mood_label": "Humor",
    "progress.energy_label": "Energía",
    "progress.stress_label": "Estrés",
    "profile.title": "Mi perfil",
    "profile.description": "Gestiona tus preferencias y configuración personal.",
    "profile.personal_info": "Información personal",
    "profile.name": "Nombre",
    "profile.email": "Correo",
    "profile.bio": "Biografía",
    "profile.bio_placeholder": "Cuéntanos sobre ti...",
    "profile.reminders": "Recordatorios y notificaciones",
    "profile.mood_reminder": "Hora del recordatorio de humor",
    "profile.journal_reminder": "Hora del recordatorio de diario",
    "profile.notifications": "Activar notificaciones",
    "profile.save": "Guardar preferencias",
    "profile.saving": "Guardando...",
    "profile.saved": "¡Preferencias actualizadas!",
    "profile.error": "Error al actualizar",
    "profile.logout": "Desconexión",
    "profile.logout_desc": "Haz clic en el botón para desconectarte de Sérénité.",
    "profile.disconnect": "Desconectarse",
    "profile.disconnecting": "Desconectando...",
    "profile.logout_success": "Desconexión exitosa",
    "profile.logout_error": "Error al desconectarse",
    "settings.title": "Configuración",
    "settings.manage": "Gestiona tus preferencias y configuración general",
    "settings.language": "Idioma",
    "settings.select_language": "Selecciona tu idioma preferido",
    "settings.theme": "Tema",
    "settings.select_theme": "Elige tu tema preferido",
    "settings.theme_light": "Claro",
    "settings.theme_dark": "Oscuro",
    "settings.notifications": "Notificaciones",
    "settings.privacy": "Privacidad",
    "settings.account": "Cuenta actual",
    "settings.user": "Usuario",
    "settings.change_name": "Cambiar nombre",
    "settings.change_name_desc": "Actualiza tu nombre de usuario",
    "settings.new_name": "Nuevo nombre",
    "settings.update_name": "Actualizar nombre",
    "settings.name_updated": "¡Nombre actualizado con éxito!",
    "settings.confirm_name": "¿Estás seguro de que quieres cambiar tu nombre?",
    "settings.logout": "Desconexión",
    "settings.logout_desc": "Haz clic para desconectarte y acceder a otra cuenta",
    "settings.disconnect": "Desconectarse",
    "settings.disconnecting": "Desconectando...",
    "settings.logout_success": "Desconexión exitosa",
    "settings.logout_error": "Error al desconectarse",
    "settings.name_error_empty": "El nombre no puede estar vacío",
    "settings.name_update_error": "Error al actualizar",
    "settings.confirm": "Confirmar",
    "settings.cancel": "Cancelar",
    "leaderboard.title": "Ranking global",
    "leaderboard.description": "Compara tu racha con otros usuarios",
    "leaderboard.rank": "Posición",
    "leaderboard.user": "Usuario",
    "leaderboard.streak": "Racha",
    "leaderboard.achievements": "Medallas",
    "leaderboard.no_users": "No hay datos de ranking disponibles",
    "leaderboard.tip_title": "Consejo",
    "leaderboard.tip_description": "Mantén tu racha haciendo tu check-in diario de humor. Cuanto más días consecutivos, más alto subirás en el ranking global.",
    "leaderboard.anonymous_user": "Usuario Anónimo",
    "challenges.title": "Desafíos semanales",
    "challenges.description": "Completa los desafíos para ganar recompensas",
    "challenges.progress": "Progreso",
    "challenges.reward": "Recompensa",
    "challenges.completed": "Completado",
    "challenges.auto_progress": "El progreso se actualiza automáticamente según tus acciones",
    "challenges.no_challenges": "No hay desafíos disponibles esta semana",
    "challenges.how_it_works": "Cómo funcionan los desafíos",
    "challenges.tip_1": "Completa los desafíos semanales para ganar puntos",
    "challenges.tip_2": "Los puntos contribuyen a tu ranking global",
    "challenges.tip_3": "Nuevos desafíos cada semana con objetivos diferentes",
    "challenges.tip_4": "Comparte tus logros con la comunidad",
    "achievements.title": "Tus Medallas",
    "achievements.no_unlocked": "Aún no has desbloqueado medallas. ¡Mantén tu racha y desbloquea hitos especiales!",
    "achievements.milestones": "Próximos Hitos",
    "achievements.milestone_7": "Semana de Oro",
    "achievements.milestone_30": "Mes Perfecto",
    "achievements.milestone_100": "Centenario",
    "achievements.milestone_365": "Campeón del Año",
    "achievements.days_of_streak": "días de racha",
    "common.points": "puntos",
    "nav.dashboard": "Panel",
    "nav.mood": "Humor",
    "nav.journal": "Diario",
    "nav.breathing": "Respiración",
    "nav.chat": "Chat",
    "nav.progress": "Progreso",
    "nav.profile": "Perfil",
    "nav.settings": "Configuración",
    "nav.leaderboard": "Ranking",
    "nav.challenges": "Desafíos",
    "nav.rewards": "Recompensas",
    "nav.export": "Exportar",
    "nav.logout": "Desconectarse",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.confirm": "Confirmar",
    "common.close": "Cerrar",
    "rewards.shop_title": "Tienda de Recompensas",
    "rewards.shop_description": "Usa tus puntos para desbloquear recompensas exclusivas",
    "rewards.your_points": "Tus puntos disponibles",
    "rewards.insufficient_points": "Puntos insuficientes",
    "rewards.redeem_button": "Canjear",
    "rewards.already_redeemed": "Ya canjeado",
    "rewards.redeemed_success": "¡Recompensa canjeada con éxito!",
    "rewards.redeem_error": "Error al canjear la recompensa",
    "rewards.no_rewards": "No hay recompensas disponibles",
    "rewards.how_it_works": "Cómo funciona",
    "rewards.tip_1": "Completa desafíos para ganar puntos",
    "rewards.tip_2": "Acumula puntos con tu racha diaria",
    "rewards.tip_3": "Usa tus puntos para recompensas exclusivas",
    "rewards.tip_4": "Desbloquea nuevas funcionalidades",
    "export.title": "Exportar Progreso",
    "export.description": "Descarga un reporte completo de tu progreso en Sérénité",
    "export.personalized_report": "Tu Reporte Personalizado",
    "export.download_html": "Descarga un reporte HTML con:",
    "export.general_stats": "Estadísticas generales",
    "export.unlocked_medals": "Medallas desbloqueadas",
    "export.mood_history": "Historial de humor",
    "export.report_format": "El reporte se descargará en formato HTML y podrá ser abierto en cualquier navegador o impreso como PDF.",
    "export.generating": "Generando...",
    "export.download_button": "Descargar Reporte",
    "export.total_points": "Puntos Totales",
    "export.medals": "Medallas",
    "export.mood_entries": "Entradas de Humor",
    "export.journal_entries": "Entradas de Diario",
    "export.tips_title": "Consejos",
    "export.tip_1": "Descarga tu reporte regularmente para hacer seguimiento a tu progreso",
    "export.tip_2": "Puedes imprimir el reporte desde tu navegador (Ctrl+P o Cmd+P)",
    "export.tip_3": "Comparte tus logros con amigos o profesionales de salud mental",
    "export.tip_4": "Los reportes incluyen datos hasta la fecha actual",
    "streak": "Racha",
  },
  en: {
    "dashboard.welcome": "Welcome",
    "dashboard.today": "Today",
    "dashboard.quick_access": "Quick Access",
    "dashboard.mood": "Log Mood",
    "dashboard.journal": "Write Journal",
    "dashboard.breathing": "Breathing Exercise",
    "dashboard.chat": "Talk to AI",
    "dashboard.stats": "Statistics",
    "dashboard.mood_entries": "Mood Entries",
    "dashboard.journal_entries": "Journal Entries",
    "dashboard.exercises": "Exercises Completed",
    "dashboard.notifications": "Notifications",
    "dashboard.recent_activity": "Recent Activity",
    "dashboard.recent_entries": "Recent Entries",
    "dashboard.recent_exercises": "Recent Exercises",
    "dashboard.no_entries": "No entries yet",
    "dashboard.no_exercises": "No exercises yet",
    "dashboard.streak": "Streak",
    "dashboard.days": "days",
    "dashboard.achievements": "Badges",
    "dashboard.leaderboard": "Leaderboard",
    "dashboard.challenges": "Challenges",
    "dashboard.export": "Export",
    "dashboard.today_mood": "Your mood today",
    "dashboard.update": "Update",
    "dashboard.mood_recorded": "You've already logged your mood today. Keep going with serenity!",
    "dashboard.mood_prompt": "How are you feeling today? Start by logging your mood.",
    "mood.title": "Mood Tracking",
    "mood.description": "How are you feeling right now? Log your emotional state.",
    "mood.select": "Select your mood",
    "mood.emotions_felt": "Emotions felt",
    "mood.very_sad": "Very Sad",
    "mood.sad": "Sad",
    "mood.neutral": "Neutral",
    "mood.happy": "Good",
    "mood.very_happy": "Very Happy",
    "mood.energy": "Energy Level",
    "mood.stress": "Stress Level",
    "mood.energy_low": "Very Low",
    "mood.energy_high": "Very High",
    "mood.stress_low": "Very Calm",
    "mood.stress_high": "Very Stressed",
    "mood.notes": "Notes (optional)",
    "mood.notes_placeholder": "Write your thoughts or what's influencing your mood...",
    "mood.save": "Save Mood",
    "mood.update": "Update Mood",
    "mood.saving": "Saving...",
    "mood.saved": "Mood saved successfully!",
    "mood.error": "Error saving mood",
    "mood.select_error": "Please select your mood",
    "mood.emotion_happy": "Happy",
    "mood.emotion_sad": "Sad",
    "mood.emotion_anxious": "Anxious",
    "mood.emotion_calm": "Calm",
    "mood.emotion_energetic": "Energetic",
    "mood.emotion_tired": "Tired",
    "mood.emotion_frustrated": "Frustrated",
    "mood.emotion_motivated": "Motivated",
    "mood.emotion_lonely": "Lonely",
    "mood.emotion_connected": "Connected",
    "journal.title": "Personal Journal",
    "journal.description": "Write your thoughts and reflections in a safe, private space.",
    "journal.new_entry": "New Entry",
    "journal.title_input": "Title",
    "journal.title_placeholder": "Entry title",
    "journal.content_input": "Content",
    "journal.content_placeholder": "Write your thoughts...",
    "journal.rating": "Day Rating",
    "journal.save": "Save",
    "journal.saving": "Saving...",
    "journal.update": "Update",
    "journal.delete": "Delete",
    "journal.edit": "Edit",
    "journal.cancel": "Cancel",
    "journal.select": "Select an entry or create a new one",
    "journal.confirm_delete": "Are you sure you want to delete this entry?",
    "journal.confirm_edit": "Are you sure you want to update this entry?",
    "journal.deleting": "Deleting...",
    "journal.updating": "Updating...",
    "journal.created": "Entry created successfully!",
    "journal.updated": "Entry updated!",
    "journal.deleted": "Entry deleted",
    "journal.error_required": "Title and content are required",
    "journal.error_create": "Error creating entry",
    "journal.error_update": "Error updating entry",
    "journal.error_delete": "Error deleting entry",
    "breathing.title": "Breathing Exercises",
    "breathing.description": "Guide yourself through breathing and relaxation techniques.",
    "breathing.select_button": "Select",
    "breathing.duration": "Duration",
    "breathing.minutes": "minutes",
    "breathing.box": "Box Breathing",
    "breathing.box_desc": "Square breathing: 4s inhale, 4s hold, 4s exhale, 4s hold",
    "breathing.4_7_8": "4-7-8 Breathing",
    "breathing.4_7_8_desc": "Calming technique: 4s inhale, 7s hold, 8s exhale",
    "breathing.deep": "Deep Breathing",
    "breathing.deep_desc": "Slow, deep breaths to relax",
    "breathing.meditation": "Guided Meditation",
    "breathing.meditation_desc": "Short meditation for mindfulness",
    "breathing.start": "Start",
    "breathing.pause": "Pause",
    "breathing.resume": "Resume",
    "breathing.complete": "Complete Exercise",
    "breathing.completing": "Saving...",
    "breathing.cancel": "Cancel",
    "breathing.inhale": "Inhale...",
    "breathing.hold": "Hold...",
    "breathing.exhale": "Exhale...",
    "breathing.breathe": "Breathe",
    "breathing.relaxation": "How do you feel? (1-5)",
    "breathing.very_stressed": "Very Stressed",
    "breathing.very_relaxed": "Very Relaxed",
    "breathing.saved": "Exercise saved!",
    "breathing.error": "Error saving exercise",
    "chat.title": "AI Assistant",
    "chat.description": "Talk to Sérénité, your mental wellness assistant.",
    "chat.send": "Send",
    "chat.placeholder": "Write your message...",
    "chat.clear": "Clear",
    "chat.confirm_clear": "Are you sure you want to clear all conversations?",
    "chat.clearing": "...",
    "chat.cleared": "All conversations have been deleted",
    "chat.error_clear": "Error deleting conversations",
    "chat.greeting": "Hello! I'm Sérénité. How can I help you today?",
    "progress.title": "Progress Tracking",
    "progress.description": "Visualize your well-being and progress over time.",
    "progress.avg_mood": "Average Mood",
    "progress.avg_energy": "Average Energy",
    "progress.entries": "Entries Logged",
    "progress.trend": "Mood Trend",
    "progress.comparison": "Level Comparison",
    "progress.no_data": "No data available. Start logging your mood!",
    "progress.no_data_short": "No data available.",
    "progress.mood_label": "Mood",
    "progress.energy_label": "Energy",
    "progress.stress_label": "Stress",
    "profile.title": "My Profile",
    "profile.description": "Manage your preferences and personal settings.",
    "profile.personal_info": "Personal Information",
    "profile.name": "Name",
    "profile.email": "Email",
    "profile.bio": "Biography",
    "profile.bio_placeholder": "Tell us about yourself...",
    "profile.reminders": "Reminders and Notifications",
    "profile.mood_reminder": "Mood Reminder Time",
    "profile.journal_reminder": "Journal Reminder Time",
    "profile.notifications": "Enable Notifications",
    "profile.save": "Save Preferences",
    "profile.saving": "Saving...",
    "profile.saved": "Preferences updated!",
    "profile.error": "Error updating preferences",
    "profile.logout": "Logout",
    "profile.logout_desc": "Click the button below to log out of Sérénité.",
    "profile.disconnect": "Disconnect",
    "profile.disconnecting": "Logging out...",
    "profile.logout_success": "Logged out successfully",
    "profile.logout_error": "Error logging out",
    "settings.title": "Settings",
    "settings.manage": "Manage your preferences and general settings",
    "settings.language": "Language",
    "settings.select_language": "Select your preferred language",
    "settings.theme": "Theme",
    "settings.select_theme": "Choose your preferred theme",
    "settings.theme_light": "Light",
    "settings.theme_dark": "Dark",
    "settings.notifications": "Notifications",
    "settings.privacy": "Privacy",
    "settings.account": "Current Account",
    "settings.user": "User",
    "settings.change_name": "Change Name",
    "settings.change_name_desc": "Update your username",
    "settings.new_name": "New Name",
    "settings.update_name": "Update Name",
    "settings.name_updated": "Name updated successfully!",
    "settings.confirm_name": "Are you sure you want to change your name?",
    "settings.logout": "Logout",
    "settings.logout_desc": "Click to logout and access another account",
    "settings.disconnect": "Disconnect",
    "settings.disconnecting": "Logging out...",
    "settings.logout_success": "Logged out successfully",
    "settings.logout_error": "Error logging out",
    "settings.name_error_empty": "Name cannot be empty",
    "settings.name_update_error": "Error updating name",
    "settings.confirm": "Confirm",
    "settings.cancel": "Cancel",
    "leaderboard.title": "Global Leaderboard",
    "leaderboard.description": "Compare your streak with other users",
    "leaderboard.rank": "Rank",
    "leaderboard.user": "User",
    "leaderboard.streak": "Streak",
    "leaderboard.achievements": "Badges",
    "leaderboard.no_users": "No leaderboard data available yet",
    "leaderboard.tip_title": "Tip",
    "leaderboard.tip_description": "Keep your streak consistent by doing your daily mood check-in. The more consecutive days, the higher you'll climb in the global ranking.",
    "leaderboard.anonymous_user": "Anonymous User",
    "challenges.title": "Weekly Challenges",
    "challenges.description": "Complete challenges to earn rewards",
    "challenges.progress": "Progress",
    "challenges.reward": "Reward",
    "challenges.completed": "Completed",
    "challenges.auto_progress": "Progress updates automatically based on your actions",
    "challenges.no_challenges": "No challenges available this week",
    "challenges.how_it_works": "How Challenges Work",
    "challenges.tip_1": "Complete weekly challenges to earn points",
    "challenges.tip_2": "Points contribute to your global ranking",
    "challenges.tip_3": "New challenges each week with different objectives",
    "challenges.tip_4": "Share your achievements with the community",
    "achievements.title": "Your Badges",
    "achievements.no_unlocked": "You haven't unlocked any badges yet. Keep your streak and unlock special milestones!",
    "achievements.milestones": "Upcoming Milestones",
    "achievements.milestone_7": "Golden Week",
    "achievements.milestone_30": "Perfect Month",
    "achievements.milestone_100": "Centennial",
    "achievements.milestone_365": "Year Champion",
    "achievements.days_of_streak": "days of streak",
    "common.points": "points",
    "nav.dashboard": "Dashboard",
    "nav.mood": "Mood",
    "nav.journal": "Journal",
    "nav.breathing": "Breathing",
    "nav.chat": "Chat",
    "nav.progress": "Progress",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "nav.leaderboard": "Leaderboard",
    "nav.challenges": "Challenges",
    "nav.rewards": "Rewards",
    "nav.export": "Export",
    "nav.logout": "Logout",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "rewards.shop_title": "Rewards Shop",
    "rewards.shop_description": "Use your points to unlock exclusive rewards",
    "rewards.your_points": "Your available points",
    "rewards.insufficient_points": "Insufficient points",
    "rewards.redeem_button": "Redeem",
    "rewards.already_redeemed": "Already redeemed",
    "rewards.redeemed_success": "Reward redeemed successfully!",
    "rewards.redeem_error": "Error redeeming reward",
    "rewards.no_rewards": "No rewards available",
    "rewards.how_it_works": "How it works",
    "rewards.tip_1": "Complete challenges to earn points",
    "rewards.tip_2": "Accumulate points with your daily streak",
    "rewards.tip_3": "Use your points for exclusive rewards",
    "rewards.tip_4": "Unlock new features",
    "export.title": "Export Progress",
    "export.description": "Download a complete report of your progress on Sérénité",
    "export.personalized_report": "Your Personalized Report",
    "export.download_html": "Download an HTML report with:",
    "export.general_stats": "General statistics",
    "export.unlocked_medals": "Unlocked medals",
    "export.mood_history": "Mood history",
    "export.report_format": "The report will be downloaded in HTML format and can be opened in any browser or printed as PDF.",
    "export.generating": "Generating...",
    "export.download_button": "Download Report",
    "export.total_points": "Total Points",
    "export.medals": "Medals",
    "export.mood_entries": "Mood Entries",
    "export.journal_entries": "Journal Entries",
    "export.tips_title": "Tips",
    "export.tip_1": "Download your report regularly to track your progress",
    "export.tip_2": "You can print the report from your browser (Ctrl+P or Cmd+P)",
    "export.tip_3": "Share your achievements with friends or mental health professionals",
    "export.tip_4": "Reports include data up to the current date",
    "streak": "Streak",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
